accounts/urls.py
from django.urls import path,include
from .import views

app_name='accounts'

urlpatterns = [
    path('signup', views.signup,name='sign_up'),
    path('profile', views.prof,name='profile'),
    path('profile/edit', views.profileEdit,name='profile_edit'),
]

job/urls.py
from django.urls import path,include

from .import views

app_name='job'

urlpatterns = [
    path('', views.Job_list,name='job_list'),
    path('add', views.add_job,name='add_job'),
    path('<str:slug>', views.Job_detail,name='job_detail'),

]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('job/', include('job.urls',namespace='jobs')),
    path('contact/', include('contact.urls',namespace='contact_us')),
]
print("this is static root")

print(settings.STATIC_ROOT)
"""
urlpatterns += staticfiles_urlpatterns()
urlpatterns = [
    # ... the rest of your URLconf goes here ...
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

"""
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.

def image_upload_name(instance,image_name):
    imgName,ext=image_name.split(".")
    return "users/%s.%s"%(instance.id,ext)

class Userprofile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    phone_number=models.CharField(max_length=15)
    img=models.ImageField(upload_to=image_upload_name)
    city=models.ForeignKey('city',related_name="user_city",on_delete=models.CASCADE,blank=True,null=True)
    def __str__(self):
        return str(self.user)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        profile.objects.create(user=instance)


class city(models.Model):
    city=models.CharField(max_length=30)
    def __str__(self):
        return self.city

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Userprofile

class signupForm(UserCreationForm):
    class Meta:
        model=User
        fields=['username','email','password1','password2']

class UserForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['username','first_name','last_name','email']

class ProfileForm(forms.ModelForm):
    class Meta:
        model=Userprofile
        fields=['city','phone_number','img']

accounts/views.py
from django.shortcuts import render,redirect
from .forms import signupForm,UserForm,ProfileForm
from django.contrib.auth import authenticate,login
from django.urls import reverse
from .models import Userprofile

# Create your views here.

def signup(request):
    if (request.method=='POST'):
        form=signupForm(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data('username')
            password=form.cleaned_data('password1')
            user=authenticate(username=username,password=password)
            login(request,user)
            return redirect(reverse('accounts/profile'))
    else:
        form=signupForm()
    return render(request,'registration/signup.html',{'form':form})


def prof(request):
    profileinst=Userprofile.objects.get(user=request.user)
    return render(request,'accounts/profile.html',{'Profiles':profileinst})



def profileEdit(request):
    profile=Userprofile.objects.get(user=request.user)
    if (request.method=='POST'):
        userform=UserForm(request.POST,instance=request.user)
        profileform=ProfileForm(request.POST,request.FILES,instance=profile)
        if userform.is_valid() and profileform.is_valid():
            userform.save()
            myprofile=profileform.save(commit=False)
            myprofile.user=request.user
            myprofile.save()
            return redirect(reverse('accounts:profile'))
    else:
        userform=UserForm(instance=request.user)
        profileform=ProfileForm(instance=profile)
    return render(request,'accounts/profile_edit.html',{'userform':userform,'profileform':profileform})

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 mx-auto">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Job Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Name: <span>{{Profiles.user.username}}</span></li>
                                <li>Email: <span>{{Profiles.user.email}}</span></li>
                                <li>Phone Number: <span>{{Profiles.phone_number}}</span></li>
                                <li>Address: <span>{{Profiles.city}}</span></li>
                            </ul>
                        </div>
                        <div class="p-5">
                          <a href="{% url 'accounts:profile_edit' %}" class="boxed-btn3 w-100">Edit profile</a>
                        </div>
                    </div>
                    <div class="share_wrap d-flex">
                        <span>Share at:</span>
                        <ul>
                            <li><a href="#"> <i class="fa fa-facebook"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-google-plus"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-twitter"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-envelope"></i></a> </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body%}

accounts/templates/accounts/profile_edit.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Edit user</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">

                    <div class="apply_job_form white-bg">
                        <h4>Edit Your Profile</h4>
                        <form action="#" method="post" enctype="multipart/form-data">
                          {% csrf_token %}
                          {% bootstrap_form userform %}
                          {% bootstrap_form profileform %}
                          {% buttons %}
                             <button class="boxed-btn3 w-100" type="submit">Edit User</button>
                          {% endbuttons %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body%}